### ISSUE TITLE
Minor doc errors

### ISSUE THREAD

**Issue by dbr** [imageworks/OpenColorIO#246]
Few minor errors in the docs:

http://opencolorio.org/installation.html#quick-environment-configuration has wrong title in link, "For prebuilt config files, see the Contributor License Agreements download section"

http://opencolorio.org/developers/bindings/PythonAPI.html#PyOpenColorIO.Config.getCacheID A few of the Python API docs have incorrect `:py:method` links

**Comment by scoopxyz** [comment]
Closed by 2b12063e22dbdbff927b5a59d04fe1e30e90c1fe
