### ISSUE TITLE
Trouble building pyglue with clang

### ISSUE THREAD

**Issue by sambler** [imageworks/OpenColorIO#333]
I am having trouble building pyglue using clang, I get no member named... errors.

    error: no member named 'addEnvironmentVar' in 'OpenColorIO::v1::Config'

It may be coincidence but the errors all match up with the ABI changes listed in [this commit](https://github.com/imageworks/OpenColorIO/commit/4527796d81036551827624cb1cbabdf0ed3144a3)

I'm on FreeBSD using clang but a quick test shows gcc46 compiles without error.

**Comment by sambler** [comment]
Current master with #380 gives me a buildable source again.

For me 1.0.9 failed to build, several fixes have been applied, with this one being the last item. Any chance we can look at applying any small outstanding build fix patches in the list and tag a new release?

**Comment by malcolmhumphreys** [comment]
@sambler does the latest master fix this issue for you?

**Comment by sambler** [comment]
yes fixed in master.
