### ISSUE TITLE
bug: search_path component is assumed to be relative if it starts with a variable

### ISSUE THREAD

**Issue by mjmvisser** [imageworks/OpenColorIO#336]
Try this:

export LUTS_PATH=/path/to/luts

``` yaml
search_path: "$LUTS_PATH:luts"
```

Try baking a lut and you'll get an error like this:

(assuming config.ocio is located in /home/mvisser/ocio)

> OCIO Error: Error baking flame:The specified file reference  'foo.csp' could not be located. The following attempts were made: /home/mvisser/ocio//path/to/luts/foo.csp : /home/mvisser/ocio/luts/foo/csp
> See --help for more info.

OCIO shouldn't assume a path component is relative until after context variables have been expanded.

**Comment by scoopxyz** [comment]
Okay to mark as closed @mjmvisser ?
