### ISSUE TITLE
Hi ,can I convert  PNGCanvas  to PIL Image ?

### ISSUE THREAD

**Issue by sunzhaoyang** [imageworks/OpenColorIO#351]
Hi ,I had read your answer:
http://stackoverflow.com/questions/12978846/python-get-screen-pixel-value-in-os-x

I want to convert  PNGCanvas to a PIL Image object without save to disk 。How can I do it ? Is Image.fromString works?

**Comment by lgritz** [comment]
Unrelated to OCIO. Closing.
