### ISSUE TITLE
FileTransform not clamping low values when applying inverse of 1D LUT

### ISSUE THREAD

**Issue by hpd** [imageworks/OpenColorIO#399]
In the case where values below the lower bound of the output range of a 1D LUT are run through the inverse of that LUT, the FileTransform does not behave as expected. Specifically, the FileTransform does not clamp values below the lower bound of the LUT output before applying the inverse LUT transform.

An example .spi1d 1D LUT is as follows
Version 1
From -0.1 2.0
Length 2
Components 1
{
         0.0
         1.0
}

A very simple Nuke script demonstrating the problem is copied below. The Red channel only covers the 0.0 to 1.0 range and inverts as expected. The green channel goes beyond the 0.0 to 1.0 range and produces large negative values for values below 0.0. Values above 1.0 are clamped properly before the inverse LUT is applied.

set cut_paste_input [stack 0]
version 9.0 v7
Constant {
 inputs 0
 channels rgb
 format "512 512 0 0 512 512 1 square_512"
 name Constant1
 selected true
 xpos -155
 ypos -111
}
Expression {
 expr0 x/(width-1)
 expr1 y/(width-1)*3-1.5
 name Expression3
 selected true
 xpos -155
 ypos -11
}
OCIOFileTransform {
 file ocio_lut_issue_spi1d
 direction inverse
 working_space linear
 name OCIOFileTransform2
 selected true
 xpos -155
 ypos 48
}

**Comment by KevinJW** [comment]
Relates to issues #391 #326 and possibly #289 #196

**Comment by KevinJW** [comment]
This may explain the problems when using ACEScc transforms in image filtering see https://www.researchgate.net/publication/305278559_A_retrospective_on_the_adoption_of_the_ACES_technology_at_Framestore

**Comment by sobotka** [comment]
Bump on this now that OCIO is back to life.

**Comment by malcolmhumphreys** [comment]
Any chance someone can do a change and a pull request for this? Should be
straightforward to add a clamp.

Longer term we could add a BOUNDS option to support both BOUNDS_EXTRAPOLATE
and BOUNDS_CLAMP.

**Comment by scoopxyz** [comment]
Not the most elegant solution, but I have submitted a hotfix #418 for this particular issue, longer term the BOUNDS parameters suggested by @malcolmhumphreys seems the best solution
