### ISSUE TITLE
Can't add a look on the config with python

### ISSUE THREAD

**Issue by pyalot** [imageworks/OpenColorIO#427]

**Comment by scoopxyz** [comment]
`PyOpenColorIO.Config.addLook()` which is passed a Look object:

**Look**
class PyOpenColorIO.Look
The Look is an ‘artistic’ image modification, in a specified image state.

The processSpace defines the ColorSpace the image is required to be in, for the math to apply correctly.

**Methods**:
createEditableCopy
getName
getProcessSpace
getTransform
isEditable
setName
setProcessSpace
setTransform

**Comment by pyalot** [comment]
The config object for getLook returns strings, not look objects. Looks don't seem to have any way to be constructed or obtained as object.

**Comment by scoopxyz** [comment]
`getLooks()` returns a list of strings for the current looks, `getLook(str)` returns a Look object.

**Comment by pyalot** [comment]
Please document

**Comment by scoopxyz** [comment]
These are documented on the website here: http://opencolorio.org/developers/bindings/PythonAPI.html

As such:
**getLook**
getLook(str)

Returns the information of a specified look in PyOpenColorIO.Config.

**Parameters:** str (string) – look
**Returns:** specified look
**Return type:** look object

**getLooks**
getLooks()

Returns a list of all the looks defined in PyOpenColorIO.Config.

**Returns:** looks
**Return type:** tuple of look objects
