### ISSUE TITLE
Houdini Log Sampling

### ISSUE THREAD

**Issue by scoopxyz** [imageworks/OpenColorIO#440]
@KevinJW seeing issues with Houdini LUTs with log sampling producing erratic results through _ociobakelut_

**Comment by KevinJW** [comment]
To be clear, OCIO doesn't support Log sampling in the baked LUTs. I was asking in another channel if anybody had tried implementing support for it (i.e. issue #287) as it mostly works around an issue I am seeing where baked LUTs don't always look correct in mplay/other Houdini tools.

The problem I have may be related to issues #383 or #137, will try see if I can understand the issue some more.

Kevin

**Comment by KevinJW** [comment]
I think I figured out the issue, just need to create a test case to catch the fault, does indeed appear to relate to #383 

Kevin

**Comment by KevinJW** [comment]
Confirmed my issue is #383, pull request #442 fixes my issue, once pulled this issue (#440) should be closed, but #287 should be left open.

Kevin
