### ISSUE TITLE
Implement tetrahedral interpolation in GPU code path

### ISSUE THREAD

**Issue by dbr** [imageworks/OpenColorIO#445]
#199 added support to this for the CPU path, but the GPU path falls back to linear when this is used, which is bad as these are not always equivalent

**Comment by Maggick-** [comment]
Does any of the LutOps work on the Gpu? They both set supportGpuShader to false and throw and exceptions saying they don't support shader generation. So I'm wondering is even the linear interpolation done on the Gpu?
(Sorry I'm new to this project)

**Comment by dbr** [comment]
I could be mistaken, and someone with a better understanding of the GPU code path could explain better, but: I think basically the Lut1D op works on the GPU the same way the Lut3D does (by being sampled/"baked" into a LUT which is looked up by built-in shader methods)

The exception raised by Lut1DOp etc says it "does not support *analytical* shader generation" (which is different to "not supported on GPU")

I'm not certain, but the Lut1DOp may need the similar work done if we add, say, cubic interpolation

**Comment by hodoulp** [comment]
OCIO GPU engine is only expecting one single 3D Lut (or none). The processor bakes the color transformation (i.e. modified the list of ops to only have at least one 3D Lut) during the finalize step (refer to Processor.cpp). Please have a look to PartitionGPUOps() in NoOps.cpp file for details.
So, only GPU 3D texture interpolation modes are available (ociodisplay app is using linear).

**Comment by hodoulp** [comment]
@dbr @Maggick-    This should be fixed now in master using the new GPU mechanism. Please refer to the GpuShaderDesc class explanations in OpenColorIO.h, utils/openglbuilder helpers and finally, the apps/ociodisplay (or ocioconvert) for a concrete implementation. 

Even if the bake mode is still supported in master (for backward compatibility), the GpuShaderDesc should be the first choice as it offers the processing parity between CPU and GPU (including the tetrahedral interpolation).

**Comment by doug-walker** [comment]
Closing this issue as fixed.
