### ISSUE TITLE
Minor website/docs tweaks

### ISSUE THREAD

**Issue by dbr** [imageworks/OpenColorIO#451]
1. http://opencolorio.org/installation.html#environment-variables should mention OCIO_ACTIVE_VIEWS, OCIO_ACTIVE_DISPLAYS, OCIO_LOGGING_LEVEL
2. The "Color Transform Example" has text "spi-animation profile, available here" which doesn't link anywhere
3. http://opencolorio.org/installation.html#building-from-source should say "Nuke 6.x or newer" probably
4. As Marc Draco [mentioned on nuke-user list](https://groups.google.com/forum/#!topic/ocio-users/kV-SrD0yGXQ), http://opencolorio.org/CompatibleSoftware.html should list Natron and probably remove Ramen as it is no longer being developed (http://est77.github.io/ramen.html "It was developed between 2008 and 2011")

**Comment by scoopxyz** [comment]
Thank you for carrying that discussion over
