### ISSUE TITLE
ninja not working because of missing dependencies 

### ISSUE THREAD

**Issue by hodoulp** [imageworks/OpenColorIO#467]
1. CMake -G Ninja ....
2. ninja
==> fails because of missing dependencies between libOpenColorIO & yaml-cpp &tinyxml libraries.

Tested on Windows & centOS 7

**Comment by hodoulp** [comment]
VC++ nmake does not have '-j' option so having ninja support would greatly speedup the build.

**Comment by boberfly** [comment]
Hey @hodoulp have you tried -G "NMake Makefiles JOM" ? You can get jom.exe from Qt they use that to build. And yep it supports -j for sure.

**Comment by hodoulp** [comment]
@boberfly thanks for the information, I will definitively have a look. 
However, I'm currently waiting a major refactoring of the OCIO makefiles around #484 before moving forward...

**Comment by hodoulp** [comment]
Windows ninja has problems with external projects. Refer to https://cmake.org/pipermail/cmake/2015-April/060234.html

But I found a tool http://wiki.qt.io/Jom which is perfectly working with nmake

**Comment by hodoulp** [comment]
Fixed by #520
