### ISSUE TITLE
Segfault with incomplete configuration settings

### ISSUE THREAD

**Issue by sobotka** [imageworks/OpenColorIO#472]
OCIO fails with incomplete configurations. Demo code to trigger the segfault:

    config = PyOpenColorIO.Config()
    config.setRole("reference", "foobar")

    try:
        config.sanityCheck()
        with open("testconfig.ocio", mode='w') as fp:
            fp.write(config.serialize())

**Comment by hodoulp** [comment]
Have a look to pull request #475

**Comment by scoopxyz** [comment]
I'll close for now, looks like it should be resolved. Will reopen if there are still issues.
