### ISSUE TITLE
Typo in Python AllocationTransform Example

### ISSUE THREAD

**Issue by sobotka** [imageworks/OpenColorIO#473]
Line 20 of https://github.com/imageworks/OpenColorIO/blob/master/docs/developers/bindings/PythonTransforms.rst
 
The constant ALLOCATION isn't present, as defined by the constants.

Should probably be a viable constant?

       # Allocation
        self.assertEqual(OCIO.Constants.ALLOCATION_UNKNOWN, "unknown")
        self.assertEqual(OCIO.Constants.ALLOCATION_UNIFORM, "uniform")
        self.assertEqual(OCIO.Constants.ALLOCATION_LG2, "lg2")

**Comment by scoopxyz** [comment]
Not sure I follow what you're saying? The constants listed above resolve to those strings.

**Comment by sobotka** [comment]
As quoted from the page:
> transform.setAllocation(OCIO.Constants.ALLOCATION)

Where "ALLOCATION" doesn't exist.

**Comment by dbr** [comment]
(made related ticket #481 - would be good to setup doctest type thing to catch errors like this in example code)
