### ISSUE TITLE
Constants aren't listed in the Python section of the docs

### ISSUE THREAD

**Issue by scoopxyz** [imageworks/OpenColorIO#493]
As mentioned in #480 by @dbr 

The Python documentation generation needs to be revisited.

**Comment by dbr** [comment]
Is this fixed? Didn't see any commits which changed the docs recently (although I didn't look closely)

**Comment by scoopxyz** [comment]
no not yet, I looked briefly and didn't see an easy way to add them. Haven't looked back recently.

I believe its because the documentation is generated from Sphinx autodocs rather than looking at the C++ bindings. I was going to wrap this into any efforts to clean up the documentation generation.
