### ISSUE TITLE
OpenColorIO 1.1.0 fails to build from source on Debian unstable/sid

### ISSUE THREAD

**Issue by mfvescovi** [imageworks/OpenColorIO#506]
Hi!

While test building latest release on Debian unstable/sid, OCIO fails due to:
> [ 37%] Building CXX object src/core/CMakeFiles/OpenColorIO.dir/NoOps.cpp.o
cd "/<<PKGBUILDDIR>>/debian/cmake/src/core" && /usr/bin/c++  -DOpenColorIO_EXPORTS -I"/<<PKGBUILDDIR>>/export" -I"/<<PKGBUILDDIR>>/debian/cmake/export" -I"/<<PKGBUILDDIR>>/ext/oiio/src/include" -I"/<<PKGBUILDDIR>>/debian/cmake/ext/dist/include"  -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wshadow -Wconversion -Wcast-qual -Wformat=2 -fPIC   -DTIXML_USE_STL   -fPIC -fvisibility=hidden -Werror -o CMakeFiles/OpenColorIO.dir/NoOps.cpp.o -c "/<<PKGBUILDDIR>>/src/core/NoOps.cpp"
/<<PKGBUILDDIR>>/src/core/MathUtils.cpp:333:10: error: 'void OpenColorIO::v1::{anonymous}::GetMxbResult(float*, float*, float*, float*)' defined but not used [-Werror=unused-function]
     void GetMxbResult(float* vout, float* m, float* x, float* v)
          ^~~~~~~~~~~~

Attached [opencolorio_1.1.0~dfsg0-1_buildlog](https://github.com/imageworks/OpenColorIO/files/1646269/opencolorio_1.1.0.dfsg0-1_buildlog.txt) is the full log.

Thanks.

**Comment by dracwyrm** [comment]
Have you tried this patch?
https://github.com/imageworks/OpenColorIO/commit/f39552d70098a98f7c1fb3b4f020b550ce2dd75a.patch
It's in the master branch. There are a few other patches that you may want to look at as well. :)

**Comment by mfvescovi** [comment]
> It's in the master branch. There are a few other patches that you may want to look at as well. :)

Then, probably, a v1.1.1 is on its way, given 1.1.0 fails to build... right? ;-)
I'm not going to cherry-pick commits randomly to get OCIO build again on Debian. :-P

**Comment by dracwyrm** [comment]
You only need that patch to make it build. I included it in the Gentoo ebuild, but with 1.1.1, I'll be able to clean up the files to remove those patches.

**Comment by mfvescovi** [comment]
OK, I've added that patch and OCIO 1.1.0 builds fine now. Thanks @dracwyrm.
Closing.
