### ISSUE TITLE
Add documentation for Python bindings of OCIO::Baker class

### ISSUE THREAD

**Issue by scoopxyz** [imageworks/OpenColorIO#515]

**Comment by michdolan** [comment]
Baker appears to already have Python bindings:
https://github.com/imageworks/OpenColorIO/blob/master/src/pyglue/PyBaker.cpp

Was there a specific part of the API missing or not functional?

**Comment by scoopxyz** [comment]
So there is, let change the title to the correct problem. There is no documentation that it exists or how to use it.
