### ISSUE TITLE
Enable override of TinyXML

### ISSUE THREAD

**Issue by abergmeier** [imageworks/OpenColorIO#538]
When building OpenColorIO, I want to use a special variant of _tinyxml_, that is available in a local path. I wonder how to best make the `find_package(TINYXML)` call use my paths instead of searching.
The obvious would be to modify `FindTinyXML.cmake` to check whether the envs are already set and then skip searching.
Would be great if you could give some pointers since I am a bit rusty with CMake.

**Comment by hodoulp** [comment]
Deprecated as we transitioned to eXpat #614
