### ISSUE TITLE
Where can I download Truelight SDK (for TruelightTransform) for Windows?

### ISSUE THREAD

**Issue by zhou-heng** [imageworks/OpenColorIO#544]
First of all, is Truelight SDK needed to build OCIO proprietory so charging money for use or freely downloadable?

If it is free, where can I download it? I searched in google but couldn't find it. Furthermore, is there any Windows version of Truelight SDK? Thanks.

**Comment by dbr** [comment]
It is proprietary and requires buying a license to access,
https://github.com/imageworks/OpenColorIO/pull/489#issuecomment-355435087

However it might be worth noting the Truelight component is optional - you can build OCIO without it (in fact it is quite uncommon to enable this - e.g the builds in software like Nuke/Maya/etc do not have it enabled as far as I'm aware)

**Comment by scoopxyz** [comment]
Closing for now, please reopen if discussion needs to continue.
