### ISSUE TITLE
Some errors when building NUKE plug-ins on Windows using VS2015

### ISSUE THREAD

**Issue by zhou-heng** [imageworks/OpenColorIO#545]
Environment:
- Windows 10 version 1803
- Visual Studio 2015 Update 3
- NUKE 10.0v4

Steps towards to the errors:
1) Download OpenColorIO master branch (version 1.1.0) and uncompress the source package.
2) Create directory `build` and cd into it.
3) In the command line, run
`cmake -DCMAKE_CONFIGURATION_TYPES=Release -DGLUT_glut_LIBRARY=C:\...\freeglut-3.0.0\install\lib\freeglut.lib -DGLUT_INCLUDE_DIR=C:\...\freeglut-3.0.0\install\include -DGLEW_INCLUDES=C:\...\glew-2.1.0-src\include -DGLEW_LIBRARIES=C:\...\glew-2.1.0-src\lib\Release\x64\glew32.lib -DPKG_CONFIG_EXECUTABLE=C:\...\pkg-config.exe -DNuke_INCLUDE_DIR="C:\Program Files\Nuke10.0v4\include" -DNuke_LIBRARIES="C:\Program Files\Nuke10.0v4\lib" -G"Visual Studio 14 2015 Win64" ..`
NUKE is recognized correctly:
> -- Found Nuke: C:/Program Files/Nuke10.0v4/include
> -- Nuke_API_VERSION: ----
> -- Will build the Nuke plugins against C:/Program Files/Nuke10.0v4
4) Add a line 
`add_definitions(-DNDK_IGNORE_VISUAL_STUDIO_VERSION_CHECK)`
at the beginning of `src\nuke\CMakeLists.txt` to bypass the version checking:
> Only plugins compiled with vs2010 are supported.
5) Open `OpenColorIO.sln` in VS2015. There are many projects that begin with "NukeOCIO". When Building these projects, I encountered the following errors:

```
10>C:\Program Files\Nuke10.0v4\include\DDImage/DDMath.h(74): error C2382: 'rint': redefinition; different exception specifications
10>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cmath(273): note: see declaration of 'rint'
10>C:\Program Files\Nuke10.0v4\include\DDImage/DDMath.h(275): error C2556: 'int signbit(float)': overloaded function differs only by return type from 'bool signbit(float) throw()'
10>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\ucrt\corecrt_math.h(305): note: see declaration of 'signbit'
10>C:\Program Files\Nuke10.0v4\include\DDImage/DDMath.h(274): error C2371: 'signbit': redefinition; different basic types
10>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\ucrt\corecrt_math.h(305): note: see declaration of 'signbit'
10>C:\Program Files\Nuke10.0v4\include\DDImage/DDMath.h(280): error C2556: 'int signbit(double)': overloaded function differs only by return type from 'bool signbit(double) throw()'
10>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\ucrt\corecrt_math.h(310): note: see declaration of 'signbit'
10>C:\Program Files\Nuke10.0v4\include\DDImage/DDMath.h(279): error C2371: 'signbit': redefinition; different basic types
10>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\ucrt\corecrt_math.h(310): note: see declaration of 'signbit'
```

I'm not sure if these errors come out because only VS2012 works in Nuke plug-in development on Windows. But I don't have VS2012 to test. If I am to use VS2015, it seems that I have to make some modifications to the Nuke's header file `DDMath.h`. Since I am not very familiar with NDK development, I submit this post here asking how to modify the `DDMath.h` to build the OCIO NUKE plug-in. Thank you.

**Comment by scoopxyz** [comment]
Closing for now, please reopen if discussion continues.
