### ISSUE TITLE
Rebind textures in OpenGLBuilder::useAllTextures

### ISSUE THREAD

**Issue by pjurkas** [imageworks/OpenColorIO#546]
We keep several OpenGLBuilder instances in LRU cache for better performance. All instances use the same texture units -- they are initialized by calling OpenGLBuilder::allocateAllTextures(4) with the same startIndex == 4. When we reuse some already cached instance by calling OpenGLBuilder::useAllTextures(), the textures are not rebind at the moment.

Can we add glBindTexture() call in the OpenGLBuilder::useAllTextures()?

**Comment by pjurkas** [comment]
`
diff --git a/src/lang-glsl/glsl.cpp b/src/lang-glsl/glsl.cpp
index 5f7f09d..44d1997 100644
--- a/src/lang-glsl/glsl.cpp
+++ b/src/lang-glsl/glsl.cpp
@@ -256,7 +256,7 @@ void OpenGLBuilder::allocateAllTextures(unsigned startIndex)
 
         // 3. Keep the texture id & name for the later enabling
 
-        m_textureIds.push_back(std::make_pair(texId, name));
+        m_textureIds.push_back({texId, name, GL_TEXTURE_3D});
 
         currIndex++;
     }
@@ -286,7 +286,8 @@ void OpenGLBuilder::allocateAllTextures(unsigned startIndex)
 
         // 3. Keep the texture id & name for the later enabling
 
-        m_textureIds.push_back(std::make_pair(texId, name));
+        unsigned type = (height > 1) ? GL_TEXTURE_2D : GL_TEXTURE_1D;
+        m_textureIds.push_back({texId, name, type});
         currIndex++;
     }
 }
@@ -296,8 +297,8 @@ void OpenGLBuilder::deleteAllTextures()
     const size_t max = m_textureIds.size();
     for(size_t idx=0; idx<max; ++idx)
     {
-        const std::pair<unsigned, std::string> data = m_textureIds[idx];
-        glDeleteTextures(1, &data.first);
+        const auto& data = m_textureIds[idx];
+        glDeleteTextures(1, &data.id);
     }
 
     m_textureIds.clear();
@@ -308,10 +309,12 @@ void OpenGLBuilder::useAllTextures()
     const size_t max = m_textureIds.size();
     for(size_t idx=0; idx<max; ++idx)
     {
-        const std::pair<unsigned, std::string> data = m_textureIds[idx];
+        const auto& data = m_textureIds[idx];
+        glActiveTexture(GL_TEXTURE0 + m_startIndex + idx);
+        glBindTexture(data.type, data.id);
         glUniform1i(
             glGetUniformLocation(m_program, 
-                                 data.second.c_str()), 
+                                 data.name.c_str()), 
                                  GLint(m_startIndex + idx) );
     }
 }
diff --git a/src/lang-glsl/glsl.h b/src/lang-glsl/glsl.h
index acfc619..539c157 100644
--- a/src/lang-glsl/glsl.h
+++ b/src/lang-glsl/glsl.h
@@ -46,7 +46,14 @@ typedef OCIO_SHARED_PTR<OpenGLBuilder> OpenGLBuilderRcPtr;
 
 class OpenGLBuilder
 {
-    typedef std::vector< std::pair<unsigned, std::string> > TextureIds;
+    struct TextureId
+    {
+        unsigned id;
+        std::string name;
+        unsigned type;
+    };
+
+    typedef std::vector< TextureId > TextureIds;
 
 public:
     // Create an OpenGL builder using the GPU shader information from a specific processor
`

**Comment by hodoulp** [comment]
Unfortunately, I have no way to test that scenario with OCIO apps. So, I would greatly appreciate if you could do it with your tool, and contact me if you need anything.
I checked the patch and it seems fine except that it's using C++11 which not yet officially authorized for OCIO.

**Comment by pjurkas** [comment]
Pre-C++11 patch:

```diff
diff --git a/src/lang-glsl/glsl.cpp b/src/lang-glsl/glsl.cpp
index 5f7f09d..0fde0aa 100644
--- a/src/lang-glsl/glsl.cpp
+++ b/src/lang-glsl/glsl.cpp
@@ -256,7 +256,7 @@ void OpenGLBuilder::allocateAllTextures(unsigned startIndex)
 
         // 3. Keep the texture id & name for the later enabling
 
-        m_textureIds.push_back(std::make_pair(texId, name));
+        m_textureIds.push_back(TextureId(texId, name, GL_TEXTURE_3D));
 
         currIndex++;
     }
@@ -286,7 +286,8 @@ void OpenGLBuilder::allocateAllTextures(unsigned startIndex)
 
         // 3. Keep the texture id & name for the later enabling
 
-        m_textureIds.push_back(std::make_pair(texId, name));
+        unsigned type = (height > 1) ? GL_TEXTURE_2D : GL_TEXTURE_1D;
+        m_textureIds.push_back(TextureId(texId, name, type));
         currIndex++;
     }
 }
@@ -296,8 +297,8 @@ void OpenGLBuilder::deleteAllTextures()
     const size_t max = m_textureIds.size();
     for(size_t idx=0; idx<max; ++idx)
     {
-        const std::pair<unsigned, std::string> data = m_textureIds[idx];
-        glDeleteTextures(1, &data.first);
+        const TextureId& data = m_textureIds[idx];
+        glDeleteTextures(1, &data.id);
     }
 
     m_textureIds.clear();
@@ -308,10 +309,12 @@ void OpenGLBuilder::useAllTextures()
     const size_t max = m_textureIds.size();
     for(size_t idx=0; idx<max; ++idx)
     {
-        const std::pair<unsigned, std::string> data = m_textureIds[idx];
+        const TextureId& data = m_textureIds[idx];
+        glActiveTexture(GL_TEXTURE0 + m_startIndex + idx);
+        glBindTexture(data.type, data.id);
         glUniform1i(
             glGetUniformLocation(m_program, 
-                                 data.second.c_str()), 
+                                 data.name.c_str()), 
                                  GLint(m_startIndex + idx) );
     }
 }
diff --git a/src/lang-glsl/glsl.h b/src/lang-glsl/glsl.h
index acfc619..154a617 100644
--- a/src/lang-glsl/glsl.h
+++ b/src/lang-glsl/glsl.h
@@ -46,7 +46,20 @@ typedef OCIO_SHARED_PTR<OpenGLBuilder> OpenGLBuilderRcPtr;
 
 class OpenGLBuilder
 {
-    typedef std::vector< std::pair<unsigned, std::string> > TextureIds;
+    struct TextureId
+    {
+        unsigned id;
+        std::string name;
+        unsigned type;
+
+        TextureId(unsigned id, const std::string& name, unsigned type):
+            id(id),
+            name(name),
+            type(type)
+        {}
+    };
+
+    typedef std::vector<TextureId> TextureIds;
 
 public:
     // Create an OpenGL builder using the GPU shader information from a specific processor
```

I have tested the patch with our tool.

**Comment by hodoulp** [comment]
Thanks for the updated patch file.

Sorry if I was not clear. I was thinking about an official pull request so that the community could comment/accept the changes, and the CI build would have validated the code.

Note: Please add the default empty constructor ( i.e. TextureId() ) to have predictable values for id & type. On the other hand, default assignation operator and copy constructor are fine.

**Comment by pjurkas** [comment]
The pull request is here -- https://github.com/imageworks/OpenColorIO/pull/552

Default empty constructor was added.

**Comment by hodoulp** [comment]
Merged
