### ISSUE TITLE
On linux, there's a cmake option USE_EXTERNAL_LCMS, but it isn't used

### ISSUE THREAD

**Issue by Thra11** [imageworks/OpenColorIO#558]
In the root CMakeLists.txt:
`option(USE_EXTERNAL_LCMS "Use system install lcms2 library." OFF)`
This option doesn't appear anywhere else in the project. To build against the system lcms, it seems you have to rely on cmake finding it.

**Comment by scoopxyz** [comment]
Addressed by #520
