### ISSUE TITLE
Inv LUT 1D - The GPU Path clamps to [0, 1]

### ISSUE THREAD

**Issue by hodoulp** [imageworks/OpenColorIO#622]
Following a comment in ocio-dev group, I did some investigations around the inverse LUT 1D and the GPU color processing is clamping the image.

Here is the link to the dicussion:
https://groups.google.com/forum/#!topic/ocio-dev/j-3IaLpBTbI

**Comment by riviera-kid** [comment]
I can confirm that inverting the 1D LUT is not working correctly in OCIO 1.1 and 2 (snapshot). 

The workaround is computing the inverse of the 1D LUT outside OCIO and providing both path in a config (from_reference + to_reference). Then it shows similar image for CPU/GPU paths (tested in OCIO v2).

Hope that it will be fixed soon  :)

**Comment by BernardLefebvre** [comment]
Since the LUT rework, it is now working fine on master.

**Comment by hodoulp** [comment]
Please refer to #640
