### ISSUE TITLE
Applications should be able to filter color spaces by category

### ISSUE THREAD

**Issue by doug-walker** [imageworks/OpenColorIO#623]
As configs become larger, it poses a usability problem for software applications.  For example the ACES config (while certainly excellent) has over 150 color spaces (not counting aliases).  Even with hierarchical menus, so many color spaces can become overwhelming for some users.

One may not be able to simply remove color spaces from the config since advanced users may need the extra color spaces.  Another solution would be to have many flavors of a given config, each for a given type of use, but that becomes difficult to manage.

Furthermore, certain types of color spaces are appropriate in certain contexts but not in others.  For example, a digital camera log space may be an appropriate choice when importing images, but may not be an appropriate choice as a working color space for a renderer.

The proposed solution is to allow an optional "categories" parameter for a ColorSpace that would contain tags that could be used by application user interfaces to filter which color spaces to show in a given menu.

So for example, one might have a config containing spaces such as:
```
  - !<ColorSpace>
    name: Sony SLog3/SGamut3
    categories: [input]

  - !<ColorSpace>
    name: ACEScg
    categories: [input, rendering]
```
(The other usual properties have been omitted from the example for clarity.)

Similar to the OCIO roles system, a recommended set of category tags and their purpose will be defined in the documentation but it will still be possible for people to add their own without requiring any code changes.  Having a well-defined set of category tags in the documentation will hopefully encourage applications to use tags in a consistent way, where possible.

The API will allow developers to easily get the set of color spaces with a given tag or tags and to perform logical operations (union, intersection, etc.) on the results.

The categories property is a v2 feature and is optional.  If it is not present, applications will show all color spaces, as in OCIO v1.

Note that the categories feature is intended to be used by config authors.  In addition it would be useful to be able to use environment variables to make color spaces inactive to a user interface, similar to the existing active_displays and active_views feature.  This feature will be proposed in a separate Issue.

**Comment by scoopxyz** [comment]
This is vey much needed.
I might suggest using the same langauge that you've desribed the feautre with to be the parameter name? That is `tags` instead of `categories`

I think the concept natually extends to the other objects like Looks. I think it would serve a useful role for Displays and Views as well, since active_displays and active_views requires external logic to determine what to populate that list with. The prefered solution is where a config author has already organized them into logical groupings like "animation" or "comp" active_views/displays for example.

**Comment by doug-walker** [comment]
Ha!  We originally called it "tags" but felt it was too generic (in a way, all the attributes under a ColorSpace could be considered tags) and felt "categories" was a bit more specific.  But if consensus emerges around another name, that's fine with us.

However I do want to clarify the purpose a bit further.  You should think of the categories attribute as controlling "which menus should this appear in" rather than "for what type of artist should this appear for".  These are two related but different pieces of information.

Perhaps "menus" would be a better name for the Yaml key than "categories"?  And it sounds like there is a need for another attribute such as "artists"?

So when deciding what ColorSpaces to show for a given menu, the application would call getColorSpaces with a specific menu tag and then could further filter it based on an artist tag.

If you look at the proposed API we posted today (PR #627), there is a new ColorSpaceSet class that may be returned by the new getColorSpaces method, so the implementation for an "artists" attribute should also return one of those so that an intersection could be taken of the two results.

What I would propose is that perhaps our new getColorSpaces method would take two strings rather than one: the first with the tag name ("menus" or "artists") and the second with the desired tag value?  And our *Category methods on the ColorSpace class could be made into more generic *Tags methods.

Please  have a look at PR #627 and let us know what other suggestions you have.

**Comment by hodoulp** [comment]
Categories are a set of strings attached to a color space where the meaning of these strings is up to the config. file writer.  Our target to allow color space filtering based on some characteristics of the color spaces (i.e. input/output or log/linear ...) and to document these categories, is only one way to use them. As suggested by Sean, filtering color spaces based on "logical groups" (i.e. animation, comp...) is potentially another way to use these categories.

Nothing forbids to have the two category 'meanings' coexisting in a config. file.  The API proposal ( #627 ) clearly allows to filter color spaces based on any 'string' part of the category attribute and to manipulate the results with classical operation of a set (i.e. union, intersection & difference).

On the other hand, the advantage to have well known and clearly documented list of categories (i.e. defining characteristics (and not usage) of the color spaces) would greatly help the applications to better display them. Having other categories more or less depending of the pipeline and/or studio would not help in solving the current display issue in the applications.

So I would suggest to first solve the current display issue with a generic & simple mechanism to not close the door to further improvements.

**Comment by scoopxyz** [comment]
I think all points are valid.

You guys as DCC authors want to be able to parse the config and show more relevant information in dropdowns, so required DCC-centric categories are useful. In many ways this that the intention of the required Roles, to give applications logical defaults. I would have to give it extra thought to think of universally understood workflow/ui categories, though you guys obviously have ideas in mind.

Me as a config maintainer, want to be able to cull the world different people see. For example, a texture artist probably only cares about 3-4 colorspaces out of the potentially hundreds, whereas a compositor may want the full list of colorspaces. For me, this also includes Views, different categories of user care about different viewers being accessible.

One potential issue with having dual categories is not satisfying the intersection between all **required** UI tags and the organizational tag. For example, if there is no intersection between the "texture department" tag and the "grading dropdown" tag... It could be added to the sanitycheck process to ensure 
* all required categories contain at least one colorspace
* all non-required tags intersect with all required tags (so a dropdown will never show colorspaces outside that tags "sphere", but also won't be empty)
* complexity grows as a user "subscribes" to more and more tags I'm a `senior` `texture` painter, on `xyz` show using this `app`

**Comment by hodoulp** [comment]
> You guys as DCC authors want to be able to parse the config and show more relevant information in dropdowns, so required DCC-centric categories are useful.

We propose a 'Color Space' centric categories (as it physically locates in the color space definition).

>One potential issue with having dual categories is not satisfying the intersection between all required UI tags and the organizational tag.

It could mean that it's two different concepts and perhaps, your need seems closer to the 'displays', 'active_displays', and 'active-views'  **or**  'roles' paradigms.

**Comment by hodoulp** [comment]
Thanks for the feedback, we are now moving forward by implementing the feature. Stay tuned :)

**Comment by scoopxyz** [comment]
Moving my question here: What categories will be required to exist via ociocheck?

This is where getting input from other DCCs about general categories of UI elements would be useful.

**Comment by doug-walker** [comment]
Sean, no Categories will be required.  If they are not present, then users will get the full list of ColorSpaces, just like today.

The goal of this PR is to put in place a mechanism so we can do some prototyping that would then lead to a proposal for a set of category names and documentation explaining their use.

Based on a suggestion from Kevin, we are thinking about creating a companion tool to ociocheck that could be helpful in validating these optional features.

**Comment by scoopxyz** [comment]
Yeah, that's fine, im not speaking to that specific PR (I've already approved). Rather about the category names you see being required for a DCC consumer.

**Comment by dekekincaid** [comment]
Conversations such as this should be in the ACES UI guidelines, updated ACES ocio config or perhaps color workflows from the VES.  These shouldn't be a requirement at the library level.

**Comment by sobotka** [comment]
Isn't OpenColorIO designed as a colour management system library? It strikes me that there are plenty of cases where no one is going to be using ACES.

It should be a requirement at the library level as it prevents appropriate colour management of UI componentry.

**Comment by dekekincaid** [comment]
Your use case seems to only think of this for categorizing the colorspaces definitions but as brought up by contrasting use cases from @doug-walker and @scoopxyz there are many axis for this feature (I can think of many others beyond those).

I rank this to workflow and best practices, not a requirement of the config.

**Comment by sobotka** [comment]
I agree that there are many axes here.

With that said, it's metadata that is absolutely mandatory to properly display UI componentry. There's no other way to achieve this without including the bare minimum amount, which means that configs designed for a particular use case are completely useless if the DCC attempts to properly manage the UI.

It would be a similar situation with roles, where we've ended up with them being optional, and as such, rather suboptimal to rely on beyond those that are triggered as missing via ociocheck.

A particular implementation can choose to simply ignore them if present. However, as a colour management library, it would be rather dire to leave them out of the V2 specification.

**Comment by dekekincaid** [comment]
Not everyone that uses ocio is a commercial DCC.  I debate that bad metadata is worse then no metadata.  I'm going to start getting a whole bunch of ocio config files from clients with everything with an "Aesthetic" category.  A majority of productions sending us specs do not employ color scientists and even majority of DI houses do not seem to consult them either.

I find this a bit like linting code.  Pep8 is a guide, but being a pep8 nazi makes you friends with no one.

**Comment by sobotka** [comment]
Ok. Suggestions on how to make UI construction work via OpenColorIO? Not knowing what is a transfer function and what is a chromaticity is pretty awful if you've ever tried building UIs with it.

**Comment by dekekincaid** [comment]
There is no one stopping you from adding these yourself.  We never actually use the configs that come with the DCC.  Every major facility maintains their own ocio config which is ever changing and evolving for each show.  I only want to show artists 2-5% of the available colorspaces in the first place.

You are talking about adding tools for an audience where 99.9% is unqualified to even use them and honestly could care less about them.  The people who are qualified can add their own categories, query it in python or open the config.ocio with a text editor.

**Comment by scoopxyz** [comment]
Opting to close this issue and open a new Issue regarding required/default categories.

**Comment by sobotka** [comment]
> Opting to close this issue with #648 being merged, and open a new Issue regarding required/default categories.

Did this ever get added on the tracker?
