### ISSUE TITLE
Conflicting definitions of PFNGLGETFRAGMENTMATERIALIVSGIXPROC

### ISSUE THREAD

**Issue by sobotka** [imageworks/OpenColorIO#635]
```
/usr/include/GL/glext.h:12080:typedef void (APIENTRYP PFNGLGETFRAGMENTMATERIALIVSGIXPROC) (GLenum face, GLenum pname, GLint *params);
/usr/include/GL/glew.h:18744:typedef void (GLAPIENTRY * PFNGLGETFRAGMENTMATERIALIVSGIXPROC) (GLenum face, GLenum pname, const GLint* data);
```
glext.h causes issues in the following packages on Debian Buster:
```
openglbuilder:
  glsl.cpp
ocioconvert:
  main.cpp
ociodisplay:
   main.cpp
GPUUnittest.cpp
```

**Comment by hodoulp** [comment]
[Here](https://github.com/xqemu/xqemu/issues/53) is the explanation of the problem.

**Comment by hobbes1069** [comment]
Running into this on Fedora and I tried using the patch based on the issue but it does not apply to the 1.1.0 release...

**Comment by sobotka** [comment]
I can update a branch to work against the v1.1.0 tag. Might be easier to grep for the glext.h however.

**Comment by hobbes1069** [comment]
Even better would be a new release :)
