### ISSUE TITLE
master branch may need higher cmake minimum

### ISSUE THREAD

**Issue by sh-coursework** [imageworks/OpenColorIO#654]
In the master branch (also, I think in scoopxyz-patch-1), the CMakeLists.txt file lists
cmake_minimum_required(VERSION 3.10)
but in the project declaration (next line), it includes
HOMEPAGE_URL http://opencolorio.org

I was trying to run cmake (3.10.2), and it was giving me really goofy errors with the string HOMEPAGE_URL or the actual url stuck in weird places. I think HOMEPAGE_URL wasn't a part of "project" until cmake 3.12
https://cmake.org/cmake/help/v3.12/command/project.html
Note that even 3.11 doesn't include it:
https://cmake.org/cmake/help/v3.11/command/project.html

So I _think_ the cmake minimum needs to be raised to 3.12.

**Comment by hodoulp** [comment]
HOMEPAGE_URL was added by [cmake pull request](https://github.com/Kitware/CMake/commit/73f9b2974c80394564e6af5b808133cba48ccf34#diff-f92de485056457cd3baa9096da54bf81) tagged as cmake versions 3.13 & 3.12.

As OCIO master, only requires cmake 3.10 the keyword must be removed.
