### ISSUE TITLE
OpenColorIO-Configs ASWF?

### ISSUE THREAD

**Issue by scoopxyz** [imageworks/OpenColorIO#661]
This is a dumb but still relevant question that I haven't heard anyone bring up...
The `OpenColorIO-Configs` repo is also moving under the ASWF control as well, right?

It doesn't have a license or much of anything honestly. Will this road-block its migration?

**Comment by lgritz** [comment]
We'll just move that at the same time.

**Comment by lgritz** [comment]
It's all "OpenColorIO" to the suits. I don't think it matters that there are technically two repos constituting OpenColorIO.
