### ISSUE TITLE
MacOS build fails - OpenColorIO/OpenColorIO.h' file not found

### ISSUE THREAD

**Issue by vvzen** [imageworks/OpenColorIO#683]
Hi everyone!

I'm trying to build OCIO on macOS Sierra (10.12.6), but the make command fails with the
```OpenColorIO/OpenColorIO.h' file not found``` error.

I'm simply following the docs: [http://opencolorio.org/installation.html#building-from-source](http://opencolorio.org/installation.html#building-from-source).
Basically I just created the `tmp/ociobuild` dir and executed
`cmake -D CMAKE_INSTALL_PREFIX=/software/ocio /source/ocio` with my custom paths instead of `/software/ocio` and `/source/ocio`.

Am I doing something wrong?
How can I get cmake to see those header files?
Thanks!

![screen shot 2019-02-26 at 18 19 56](https://user-images.githubusercontent.com/10340139/53432845-93bd3e80-39f3-11e9-9627-e22e948f1f8d.png)

**Comment by hodoulp** [comment]
@vvzen Which OCIO version are you compiling? i.e. master or RB-1.1

For master & RB-1-1, the build directory content is suspicious. Some files/directories are missing. In fact, it seems to be the src subdirectory content!

Here are the simplified steps:

1. **git clone https://github.com/imageworks/OpenColorIO.git ocio**
2. **cd ocio**
3. **mkdir build**
4. **cd build**
5. **cmake ..**
6. **make**

Hoping it will help you.

Note: Next time you could use [google ocio-dev](https://groups.google.com/forum/#!forum/ocio-dev) to have much more feedback from the community (note: OCIO groups will soon transition to [ASWF ocio-dev](https://lists.aswf.io/g/ocio-dev/topics)).

**Comment by vvzen** [comment]
Definitely helped! I was using the src folder instead of the ocio dir.
I've successfully managed to install both OIIO and OCIO!
Thanks a lot!
