### ISSUE TITLE
Config::getDefaultView does not respect active_views in the config.ocio

### ISSUE THREAD

**Issue by fnalex** [imageworks/OpenColorIO#754]
Using the config from here: https://github.com/imageworks/OpenColorIO-Configs/blob/master/nuke-default/config.ocio#L18-L25

I executed the following code:

```
#include <string>
#include <iostream>
#include <OpenColorIO/OpenColorIO.h>

namespace OCIO = OCIO_NAMESPACE;

int main()
{
  std::cout << "Using OCIO Version : " << OCIO_VERSION << std::endl;

  const std::string configPath = "/workspace/downloads/OpenColorIO-Configs/nuke-default/config.ocio";
  const auto config = OCIO::Config::CreateFromFile(configPath.c_str());

  const auto defaultDisplay = config->getDefaultDisplay();
  std::cout << "default display    : " << defaultDisplay << std::endl;
  const auto defaultView = config->getDefaultView(defaultDisplay);
  std::cout << "default view       : " << defaultView << std::endl;

  return 0;
}
```

Which outputs:

> Using OCIO Version : 1.1.0
> default display    : default
> default view       : None

But in the config the active_views is set to [sRGB]. So I would expect the default view to be sRGB instead of None. I came to this conclusion from here: http://opencolorio.org/userguide/config_syntax.html#displays

> Unless the active_displays and active_views sections are defined, the first display and first view will be the default.

**Comment by michdolan** [comment]
Can you try OCIO v1.1.1? This release includes some fixes related to default display and view handling.

https://github.com/imageworks/OpenColorIO/releases/tag/v1.1.1

**Comment by fnalex** [comment]
Yeah that seems to be working in 1.1.1, I'll close this issue.

> Using OCIO Version : 1.1.1
> default display    : default
> default view       : sRGB

**Comment by hodoulp** [comment]
@michdolan `master` should work as all v1.1.1 fixes are in both branches.

**Comment by hodoulp** [comment]
`master` and `v1.1.1` are working fine.
