### ISSUE TITLE
ALWAYS Trying to install ALREADY-installed packages...

### ISSUE THREAD

**Issue by jiapei100** [imageworks/OpenColorIO#820]
I've already **had** OpenEXR installed from the repository on my Ubuntu 19.04 .  There seems to be **NO Point** to have it installed again due to the scripts under **share** ? Why the current version **always** requests to install OpenEXR from scratch?

**Comment by michdolan** [comment]
Please specify what version of OCIO you are trying to build. Are you building from a release, or from the master branch?

If you are building from master, currently by default OCIO will check for required dependencies in platform-specific standard locations on your system. If they are not found, they will be downloaded and built within the build dir, and statically linked to OCIO.

You have full control of this behavior. If you don't want any dependencies to be downloaded, specify -DOCIO_INSTALL_EXT_PACKAGES=NONE in your cmake command. If the dependencies (i.e. OpenEXR) are in non-standard locations and not found, it is your responsibility to tell OCIO where to find them, by defining package specific cmake variables like -DILMBASE_DIRS=/path/to/OpenEXR.

Please see the following documentation, in the "Building from source" section, for an explanation of this behavior:
https://github.com/imageworks/OpenColorIO/blob/master/docs/installation.rst

**Comment by jiapei100** [comment]
1. OCIO_INSTALL_EXT_PACKAGES=NONE
2. Modify ext/CMakeLists.txt, 
`set(ILMBASE_MIN_VERSION 2.3.0)` to `set(ILMBASE_MIN_VERSION 2.2.0)`
