### ISSUE TITLE
Python Bindings - pybind11 vs. private destructor

### ISSUE THREAD

**Issue by hodoulp** [imageworks/OpenColorIO#828]
At the last TSC meeting, we discussed of the `pybind11` issues with private destructors and Larry mentioned that OIIO successfully implemented `pybind11`. So, I checked the `ImageInput` class from OIIO. For example, `ImageInput` has a protected constructor but a public destructor. The class also overloads the new and delete operators. And it uses a `std::unique_ptr`.
OCIO declares all the public classes with private constructor and destructor operators and uses a `std::shared_ptr`. The static method XX::Create creates a `std::shared_ptr` using `std::shared_ptr<XX>(new XX(), &XX::deleter)`.

The OIIO approach works well i.e. the new/delete operator used are those implemented by the class.  And enforcing the two operators to be all in the source file guaranties the memory management policy. The OCIO dynamic library controls the allocate/deallocate of its instances.

Following some investigations to validate the OIIO approach, I discovered that the `std::make_shared<>` never uses the overloaded new/delete operators unlike `std::shared_ptr<>`, `std::unique_ptr` and `std::make_unique<>`. In fact, `std::make_shared` creates an aggregated buffer (i.e. a single allocation) containing some data (i.e. some shared pointer data I assume) and the requested data (i.e. class instance data). That ‘optimization/behavior’ could explain why it does not use the overloaded new/delete operators.

From http://www.cplusplus.com/reference/memory/make_shared/:
`This function uses ::new to allocate storage for the object. ` It clearly states that `std::make_shared` only uses the global new operator.

The second aspect is that the destructor is public polluting the API and allowing something really bad `delete p.get()` on any OCIO public classes.

**In conclusion**, using the overloading approach means to **forbid** `std::make_shared` for all the `XX::Create` methods part of the public API when compiling a dynamic library, and polluting the public API with a dangerous method. Two weaknesses added to comply with `pybind11`.

Below is the code to investigate the new/delete operators versus the memory management utilities:
```
#include <iostream>
#include <memory>

//
// The following methods are the overloaded global new/delete operators.
//
void * operator new(size_t size)
{
        void * ptr = ::malloc(size);
        std::cout << "Global --> new " << size << " bytes: " << ptr << "\n";
        return ptr;
}

void * operator new[](size_t size)
{
        void * ptr = ::malloc(size);
        std::cout << "Global --> new[] " << size << " bytes: " << ptr << "\n";
        return ptr;
}

void operator delete(void * ptr)
{
        std::cout << "Global --> delete: " << ptr << "\n";
        ::free(ptr);
}

void operator delete[](void * ptr)
{
        std::cout << "Global --> delete[]: " << ptr << "\n";
        ::free(ptr);
}


class MyClass
{
public:
        MyClass() { std::cout << "MyClass::MyClass: " << this << "\n"; }
        ~MyClass() { std::cout << "MyClass::~MyClass: " << this << "\n"; }

        // Useless method to only check that the class instance is correctly created in memory.
        void useIt() const { std::cout << "\tMyClass:useIt()\n"; }

#ifdef CUSTOM_NEW
        // Overloaded new operator.
        void * operator new (size_t size)
        {
                void * ptr = ::operator new(size);
                std::cout << "MyClass::new " << size << " bytes: " << ptr << "\n";
                return ptr;
        }

        // Overloaded delete operator.
        void operator delete (void * ptr)
        {
                std::cout << "MyClass::delete: " << ptr << "\n";
                ::operator delete(ptr);
        }
#endif

private:
        // Useless data to avoid potential optimizations based on the class instance size.
        char arbitrary[100]{ 0 };
};

int main()
{
        std::cout << "*******************\n";
        {
                std::cout << "new MyClass\n";
                std::cout << "**\n";
                MyClass * p = new MyClass;
                p->useIt();
                delete p;
        }
        std::cout << "\n";

        std::cout << "*******************\n";
        {
                std::cout << "std::shared_ptr<MyClass>(new MyClass)\n";
                std::cout << "**\n";
                std::shared_ptr<MyClass> p = std::shared_ptr<MyClass>(new MyClass);
                p->useIt();
        }
        std::cout << "\n";

        std::cout << "*******************\n";
        {
                std::cout << "std::make_shared<MyClass>()\n";
                std::cout << "**\n";
                std::shared_ptr<MyClass> p = std::make_shared<MyClass>();
                p->useIt();
        }
        std::cout << "\n";

        std::cout << "*******************\n";
        {
                std::cout << "std::unique_ptr<MyClass>(new MyClass)\n";
                std::cout << "**\n";
                std::unique_ptr<MyClass> p = std::unique_ptr<MyClass>(new MyClass);
                p->useIt();
        }
        std::cout << "\n";

        std::cout << "*******************\n";
        {
                std::cout << "std::make_unique<MyClass>()\n";
                std::cout << "**\n";
                std::unique_ptr<MyClass> p = std::make_unique<MyClass>();
                p->useIt();
        }
        std::cout << "\n";

        return 1;
}
```

// Use the overloaded new/delete operators
`g++ -Wall -std=c++17 -O0 -DCUSTOM_NEW main.cpp`
// Use the global new/delete operators
`g++ -Wall -std=c++17 -O0 main.cpp`

**So potential changes could be:**

Below is the original pseudo code:
```
class Config
{
public:
        static ConfigRcPtr Create();

private:
        Config();
        ~Config();
        
        Config(const Config &) = delete;
        Config& operator= (const Config &) = delete;
        
        static void deleter(Config* c);
};
```
**WIP** Below is a potential pseudo code:
```
class Config
{
public:
        static ConfigRcPtr Create();

        ~Config();  // <-- Useless for a user and dangerous.

private:
        Config();

        Config(const Config &) = delete;
        Config& operator= (const Config &) =delete;

        // Is that better than the former deleter?
        void * operator new(size_t size); 
        void operator delete(void * ptr); 
};
```

**Comment by hodoulp** [comment]
Tomorrow, I will continue the investigation by looking at the move semantic.

**Comment by hodoulp** [comment]
In the meantime, any comments/questions are welcome.

**Comment by hodoulp** [comment]
Here is another proposal where the constructor & destructor remain private and the memory is well managed. The design is to offer a `shared_ptr` and also a `unique_ptr` in the public C++ API.

**(5)**
```
class Faa
{

[...]

public:
	using unique_ptr = std::unique_ptr<Faa, Deleter>;
	using shared_ptr = std::shared_ptr<Faa>;

	static unique_ptr CreateUnique() { return unique_ptr(new Faa, Deleter()); }
	static shared_ptr Create()       { return shared_ptr(new Faa, Deleter()); }

	unsigned get() const { return m_i; }
	void set(unsigned i) { m_i = i; }
};
```
```
PYBIND11_MODULE(PyOpenColorIO, m)
{
    py::class_<Faa, Faa::unique_ptr>(m, "Faa")
        .def(py::init(&Faa::CreateUnique))
        .def_property("i", &Faa::get, &Faa::set);
}
```

Whatever is the underlying pointer type, `Python` is by design reference counting instances. So, the shared instance request is done by `Python`.

Below is an example where the underlying instance is in a `std::unique_ptr` but two names (i.e. instances in C++) exist at the same time:
```
import unittest
import PyOpenColorIO as OCIO

class TransformsTest(unittest.TestCase):

    def test_interface(self):
		faa = OCIO.Faa()
		faa.i = 10
		self.assertEqual(faa.i, 10)
		faa1 = faa
		faa.i = 20
		self.assertEqual(faa.i, 20)
		self.assertEqual(faa1.i, 20)
		faa1 = None

		# As expected, the line below crashes
		#self.assertEqual(faa1.i, 20)

		# Line below succeeds because the instance is ref. counted
		self.assertEqual(faa.i, 20)
		faa = None

		# As expected, the lines below crash
		#self.assertEqual(faa.i, 20)
		#self.assertEqual(faa1.i, 20)
```

**Comment by hodoulp** [comment]
To not have a public destructor, `pybind11` imposes `std::unique_ptr` but OCIO only provides `std::shared_ptr`. For backward compatibility reason the class has the two offers, but I agree that's quite confusing.

*Note 1:*
On the other hand, does it make sense to offer a shareable `Config` instance?
But it make sense for `Processor` & `CPUProcessor` instances for example.

*Note 2:*
Finally, a `std::shared_ptr` can always be created from a `std::unique_ptr` if needed:
```
Faa::unique_ptr u(Faa::CreateUnique());
Faa::shared_ptr s(std::move(u));
```

**Comment by michdolan** [comment]
Thanks for all your investigations @hodoulp ! 

The question becomes, how much do we change core OCIO to support cleaner, easier to maintain, Python bindings. From an architectural point of view, what is there to gain or lose from moving to unique_ptr at a core level (where possible). I think it makes sense to use unique_ptr where shared_ptr is not practically needed, but for the cases where it is, and Python bindings are also needed, we're back to the original problem.

Could it be possible to have the OCIO public interface use unique_ptr exclusively, and reserve use of shared_ptr to internal use, or for classes where a public destructor is safe?

**Comment by hodoulp** [comment]
The goal of all these investigations was to preserve the `pybind11` simplicity and the existing C++ public API.

Unfortunately only solutions with some various level of refactoring of the C++ public API enable the use of a `std::shared_ptr` with `pybind11`.

So my proposal is to have a public destructor while maintaining a private constructor ( i.e. proposal **(1)** ) which is very small & easy change and keep `pybind11` binding trivial. Anyway, the potential problem `delete ptr.get()` exists for any classes using `std::unique_ptr` and `std::shared_ptr` so the C++ public API does not any extra weakness.

**Comment by lgritz** [comment]
This makes it look simple:

https://pybind11.readthedocs.io/en/stable/advanced/smart_ptrs.html#std-shared-ptr

**Comment by hodoulp** [comment]
Agreement on the **(1)** proposal so I close the issue.
